#!/usr/bin/env bash

set -o errexit

# Create a container
container=$(buildah from --name reposync registry.access.redhat.com/rhel7)

# Labels are part of the "buildah config" command
buildah config --created-by "Tinsjourney" $container
buildah config --author "tintin@gnali.org @tinsjourney" --label name=reposync $container
buildah config --label run="podman run -dt --name reposync -v \${PWD}/myconfig.env:/usr/local/etc/config.env:ro,Z -v \$\{PWD\}/repo:/var/www/html:rw,Z IMAGE" $container

# Copy the binary inside the container
buildah run $container curl -sLo /usr/local/bin/rh_reposync.sh https://raw.githubusercontent.com/tinsjourney/misc/master/rh_reposync.sh
buildah run $container chmod +x /usr/local/bin/rh_reposync.sh

# Copy default config file inside the container
buildah copy $container config.env /usr/local/etc/
buildah config --env CONFIG="/usr/local/etc/config.env" $container

# Default volume
buildah config --volume /var/www/html $container

# Define entrypoint
buildah config --entrypoint '["/usr/local/bin/rh_reposync.sh"]' $container

# Finally saves the running container to an image and remove building container
buildah commit --rm $container reposync:$(date +%Y%m%d)

# Push images to external repository
# buildah push reposync:$(date +%Y%m%d) docker://quay.io/tinsjourney/reposync:$(date +%Y%m%d)
# buildah push reposync:$(date +%Y%m%d) docker://docker.io/tinsjourney/reposync:$(date +%Y%m%d)
# buildah push reposync:$(date +%Y%m%d) docker://docker.io/tinsjourney/reposync:latest
